import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  bool isEn = true;

  Map<String, Object> textsAr = {
    "start": "أبدأ الان",
    "Tap back again to leave": "أضغط مرة أخري للمغادرة",
    'Saved successfully': 'تم الحفظ',
    "drawer_name": "عالم الطبخ",
    "drawer_item1": "الوجبات",
    "drawer_item2": "فلتر",
    "drawer_item3": "المظهر",
    "drawer_switch_title": "اختر لغتك",
    "drawer_switch_item1": "الانجليزية",
    "drawer_switch_item2": "العربية",
    "theme_appBar_title": "نمط التطبيق",
    "theme_screen_title": "قم بتعديل أنماط تطبيقك",
    "theme_mode_title": "أختر مظهر لتطبيقك",
    "System_default_theme": "مظهر الجهاز الافتراضي",
    "light_theme": "المظهر الفاتح",
    "dark_theme": "المظهر الداكن",
    "primary": "أختر اللون الاساسي",
    "accent": "أختر اللون الثانوي",
    "filters_appBar_title": "فلاترك",
    "Save": "حفظ",
    "filters_screen_title": "قم بتعديل فلاتر تطبيقك",
    "Gluten-free": "خالي من الكلوتين",
    "Gluten-free-sub": "يتضمن فقط الاطعمة الخالية من الكلوتين",
    "Lactose-free": "خالي من اللاكتوز",
    "Lactose-free_sub": "يتضمن فقط الاطعمة الخالية من مشتقات الحليب",
    "Vegetarian": "نباتي",
    "Vegetarian-sub": "يتضمن الاطعمة الخالية من المنتجات الحيوانية",
    "Vegan": "نباتي",
    "Vegan-sub": "يتضمن فقط الاطعمة الخالية من المنتجات الحيوانية ومشتقاتها",
    "categories": "التصنيفات",
    "your_favorites": "أطعمتك المفضلة",
    "cat-c1": "أيطاليا",
    "cat-c2": "أسبانيا",
    "cat-c3": "فرنسا",
    "cat-c4": "اليونان",
    "cat-c5": "بريطانيا",
    "cat-c6": "الصين",
    "cat-c7": "الهند",
    "cat-c8": "اليابان",
    "cat-c9": "تايلاند",
    "cat-c10": "الولايات المتحدة الامريكية",
    "cat-c11": "المكسيك",
    "cat-c12": "البرازيل",
    "cat-c13": "الارجنتين",
    "cat-c14": "المغرب",
    "cat-c15": "لبنان",
    "cat-c16": "تونس",
    "cat-c17": "الجزائر",
    "cat-c18": "مصر",
    "cat-c19": "سوريا",
    "cat-c20": "جنوب أفريقيا",
    "Complexity.Simple": "سهلة",
    "Complexity.Challenging": "متوسطة",
    "Complexity.Hard": "صعبة",
    "Affordability.Affordable": "غير مكلفة",
    "Affordability.Pricey": "مكلفة",
    "Affordability.Luxurious": "باهضة الثمن",
    "min": "دقيقة",
    "min2": "دقائق",
    "meal-m1": "لازانيا باللحم المفروم",
    "meal-m2": "ريزوتو",
    "meal-m3": "سباغيتي كربونارا",
    "meal-m4": "شريحة وينر",
    "meal-m5": "سلطة مع سلمون مدخن",
    "meal-m6": "موس البرتقال اللذيذ",
    "meal-m7": "الفطائر",
    "meal-m8": "دجاج بالكاري الهندي بالكريمة",
    "meal-m9": "سوفلي الشوكولاته",
    "meal-m10": "سلطة الهليون مع الطماطم الكرزية",
    "Ingredients": "المكونات",
    "Steps": "الخطوات",
    "favorites_text":
        "لم تقم بأضافة طعام مفضل لحد الآن - قم بأضافة بعض الاطعمة!",
    "ingredients-m1": [
      " شرائح لازانيا",
      "500 جرام لحم مفروم",
      "حبتين بصل مفروم",
      " حبيتين ثوم مفروم",
      "كوب جبنة موتزاريلا مبروشة",
      "1/2كوب جبنة بارميزان مبروشة",
      "كوب صلصة طماطم",
      "ملعقة كبيرة معجون طماطم",
      " 100 جرام زبدة",
      "ملعقة صغيرة ريحان",
      "1/2ملعقة صغيرة فلفل أسود",
      "رشة ملح",
    ],
    "ingredients-m2": [
      "3 كوب ماء",
      " 2 كوب وثلث مرق الدجاج",
      "ربع كوب زبدة",
      "نصف بصلة مفرومة",
      "كوب أرز",
      "نصف كوب كريمة طهي",
      "ربع كوب جبن بارميزان مبشور",
      "ملح وفلفل حسب الرغبة",
      "بقدونس مفروم للتزيين",
    ],
    "ingredients-m3": [
      "بيكون حبش مقطّع - 100 غرام",
      "جبن بارميزان - 100 غرام",
      "بيض - 3",
      "معكرونة سباغيتي رفيعة - 350 غرام",
      "ثوم مقّشر - فصّان",
      "زبدة غير مملّحة - 50 غرام",
      "ملح - بحسب الرغبة",
      "فلفل - بحسب الرغبة",
    ],
    "ingredients-m4": [
      "8 شرحات لحم بتلو",
      '4 بيضات',
      "200 جرام فتات الخبز",
      "100 جرام طحين",
      "300 مل زبدة",
      "100 جرام زيت نباتي",
      'ملح',
      'شرائح ليمون',
    ],
    "ingredients-m5": [
      'جرجير',
      "خس الضأن",
      'بقدونس',
      'الشمرة',
      "200 جرام سالمون مدخن",
      'خردل',
      'الخل البلسمي',
      'زيت الزيتون',
      'ملح وفلفل',
    ],
    "ingredients-m6": [
      "4 صفائح من الجيلاتين",
      "150 مل عصير برتقال",
      "80 جرام سكر",
      "300 جرام زبادي",
      "200 جرام كريم",
      "قشر البرتقال",
    ],
    "ingredients-m7": [
      "1 نصف كوب طحين لجميع الأغراض",
      "3 نصف ملاعق صغيرة من مسحوق الخبز",
      '1 ملعقة صغيرة ملح',
      "1 ملعقة كبيرة سكر أبيض",
      "1 ربع كوب حليب",
      '1 بيضة',
      "3 ملاعق كبيرة زبدة مذابة",
    ],
    "ingredients-m8": [
      "4 صدور دجاج",
      "1 بصلة",
      "2 فص ثوم",
      "قطعة واحدة من الزنجبيل",
      "4 ملاعق كبيرة لوز",
      "1 ملعقة صغيرة فلفل كايين",
      "500 مل من حليب جوز الهند",
    ],
    "ingredients-m9": [
      "1 ملعقة صغيرة زبدة مذابة",
      "2 ملاعق كبيرة سكر أبيض",
      "2 أوقية 70٪ شوكولاتة داكنة ، مقطعة إلى قطع",
      "1 ملعقة كبيرة زبدة",
      "1 ملعقة كبيرة طحين لجميع الأغراض",
      "4 1/3 ملاعق كبيرة من الحليب البارد",
      "1 رشة ملح",
      "1 رشة فلفل كايين",
      "1 صفار بيض كبير",
      "2 بياض بيض كبير",
      "رشة من كريمة التارتار",
      "1 ملعقة كبيرة سكر أبيض",
    ],
    "ingredients-m10": [
      "الهليون الأبيض والأخضر",
      "30 جرام صنوبر",
      "300 جرام من الطماطم الكرز",
      'سلطة',
      "ملح وفلفل وزيت زيتون",
    ],
    "steps-m1": [
      "يتم تحضير البشاميل من خلال وضع إناء على النار، ثم نذوب فيه مكعبات الزبد، ونضيف الدقيق، ويقلب بملعقة خشب حتى يتشرب كل الزبد.",
      "نضع الحليب تدريجياً مع التقليب أثناء سكبه، حتى لا تأتى كتل داخل البشاميل، وعندما يصبح الخليط متجانس نغلق النار ونضع الفلفل الأسود والملح",
      " أما بالنسبة لحشوة اللازانيا، فنضع وعاء آخر على النار، ونذوب فيه مكعبات الزبدة، ثم يضاف البصل والثوم المفروم ويقلى حتى يذبل",
      "تضاف اللحمة وتقلى حتى يتغير لونها، ثم نتبلها بالقرفة، والفلفل الأسود والملح، وتقلب جيداً.",
      "نضيف صلصة ومعجون الطماطم، ونضع الماء على اللحمة وتترك على نار هادئة مع التحريك، حتى تنضج اللحمة كلياً ونرفعها من على النار.",
      "نحضر صينية فرن زجاجية، ونسكب طبقة من البشاميل، تغطى بطبقة من شرايح اللازانيا، وتوزع فوقها طبقة من الحشوة ثم طبقة اخرى من البشاميل وفوقها طبقة من جبنة الموتزاريلا، تكرر العملية حتى تنتهى الكمية.",
      " رش الجبن البارميزان على الوجه، ثم ندخل الصينية إلى الفرن، وتترك لمدة ما بين 25 إلى 30 دقيقة.",
      "  نخرجها من الفرن وتقدم ساخنة.",
    ],
    "steps-m2": [
      " سخّني الماء مع المرق على نار متوسطة حتى تغلي، خففي النار واتركيها على النار.",
      " اذيبي 2 ملعقة كيبرة زبدة في قدر على نار متوسطة واضيفي البصل وقلّبي حتى يذبل.",
      " اضيفي الأرز وقلّبي لمدة دقيقتين، ثم اضيفي ثلث كوب من مزيج المرق والماء، وقلّبي حتى يتم امتصاصه.",
      "ارفعي درجة حرارة النار واضيفي كوب آخر من المرق، ثم دعي القدر على النار بدون أن تغطيه حتى يتم امتصاص السوائل كلها.",
      " كرري هذه الخطوة بإضافة كوب من المرق في كل مرة والانتظار حتى يتم امتصاصها حتى تنتهي كمية المرق.",
      "  دعيه على النار لمدة 25 دقيقة حتى يصبح قوامه كالكريمة.",
      " اضيفي الكريمة، الجبنة، الملح والفلفل وباقي كمية الزبدة، قلّبي لمدة دقيقتين.",
      " زيّنيه بالبقدونس وقدميه.",
    ],
    "steps-m3": [
      "في وعاء، أخفقي البيض ثمّ رشّي الفلفل واخلطي. أتركي المزيج جانباً.",
      "ضعي قدراً من الماء على النار حتى الغليان.",
      " أضيفي ملعقة صغيرة من الملح إلى الماء المغلي.",
      " ضعي المعكرونة واتركيها حتى يغلي الماء من جديد.",
      " غطّي القدر واتركي المعكرونة حوالى 10 دقائق أو حتى تنضج.",
      " إهرسي الثوم قليلاً بواسطة الجهة الملساء من السكين.",
      " في مقلاة، ذوّبي الزبدة وقلّي البيكون مع الثوم حوالى 5 دقائق حى تنضج قطع الحبش.",
      "  أخرجي الثوم من المقلاة وخففي الحرارة تحت المقلاة.",
      "  عندما تنضج المعكرونة، أخرجيها بواسطة الملعقة المخصصة للمعكرونة وصفيّها من مائها ثمّ ضعيها في المقلاة فوق البيكون.",
      " أخلطي جبن البارميزان مع البيض المخفوق.",
      "  أطفئي النار تحت المقلاة.",
      " أسكبي خليط البيض فوق المعكرونة.",
      "  أخلطي المعكرونة ببعضها حتى تمتزج.",
      " نكّهي بالملح والفلفل بحسب الرغبة.",
      " قدّمي المعكرونة فوراًمع توزيع المزيد من الجبن والفلفل الأسود على الوجه.",
    ],
    "steps-m4": [
      "طرية لحم العجل إلى حوالي 2-4 مم ، والملح على الجانبين.",
      "على طبق مسطح ، حرك البيض لفترة وجيزة بالشوكة",
      "غلفي شرائح اللحم بقليل من الدقيق ثم اغمسيها في البيضة ، وأخيراً ضعيها في فتات الخبز",
      "  سخني الزبدة والزيت في مقلاة كبيرة (اتركي الدهن يسخن بشدة) واقلي شرائح اللحم حتى يصبح لونها بنياً ذهبياً من كلا الجانبين.",
      "تأكد من قلب المقلاة بانتظام حتى تكون شرائح اللحم محاطة بالزيت ويصبح الفتات رقيقًا",
      "قم بإزالة ، وصفي على ورق المطبخ. يقلى البقدونس في الزيت المتبقي ويصفى.",
      "ضع شنيتزل على طبق ساخن وقدم مزينًا بالبقدونس وشرائح الليمون",
    ],
    "steps-m5": [
      "اغسل وقطع السلطة والأعشاب ،",
      "قطع السلمون إلى مكعبات ،",
      "قم بتحويل الخردل والخل وزيت الزيتون إلى صلصة",
      "تحضير السلطة",
      "أضف مكعبات السلمون والصلصة",
    ],
    "steps-m6": [
      "حل الجيلاتين في وعاء",
      " أضف عصير البرتقال والسكر ،",
      "انزع القدر من على الموقد",
      "- إضافة 2 ملاعق كبيرة من الزباد",
      "  قلّب الجيلاتين تحت الزبادي المتبقي ،",
      "تبريد كل شيء في الثلاجة",
      "اخفقي الكريمة وارفعيها تحت كتلة البرتقال",
      "تبرد مرة أخرى لمدة 4 ساعات على الأقل",
      "يقدم مع قشر البرتقال ،",
    ],
    "steps-m7": [
      "في وعاء كبير ، نخلط الدقيق والبيكنج بودر والملح والسكر.",
      "اصنع حفرة في المنتصف واسكب الحليب والبيض والزبدة المذابة ؛ امزج حتى تصبح ناعمة.",
      " قم بتسخين مقلاة أو مقلاة مدهونة قليلاً بالزيت على نار متوسطة عالية.",
      "صب الخليط أو اغرفه على صينية الخبز ، باستخدام ربع كوب تقريبًا لكل فطيرة. غواياكيل، الاكوادور.",
    ],
    "steps-m8": [
      "قطع صدر الدجاج إلى شرائح وقليها ،",
      "يُطحن البصل والثوم والزنجبيل إلى عجينة ويقلى كل شيء",
      "أضف البهارات وقلي القلي",
      " أضف صدور الدجاج + 250 مل من الماء واطبخ كل شيء لمدة 10 دقائق ،",
      "  أضف حليب جوز الهند ،",
      "  يقدم مع الأرز",
    ],
    "steps-m9": [
      "سخني الفرن إلى 190 درجة مئوية. قم بتبطين ورقة خبز مطوية بورق زبدة.",
      'ادهنوا قاع وجوانب 2 رامكين برفق بملعقة صغيرة من الزبدة المذابة ؛ تغطية القاع والجوانب حتى الحافة. ​​',
      "أضيفي ملعقة كبيرة من السكر الأبيض إلى رامكينز. قم بتدوير القوالب حتى يغطي السكر جميع الأسطح.",
      " ضع قطع الشوكولاته في وعاء خلط معدني.",
      "ضع وعاءً فوق قدر به حوالي 3 أكواب من الماء الساخن على نار خفيفة.",
      "تذوب 1 ملعقة كبيرة زبدة في مقلاة على نار متوسطة. يرش الدقيق. اخفقي حتى يندمج الدقيق مع الزبدة ويثخن الخليط.",
      "اخفقي في الحليب البارد حتى يصبح المزيج ناعما و يثخن. نقل الخليط إلى وعاء مع الشوكولاتة المذابة.",
      "أضف الملح والفلفل الحار. تخلط جيدا. أضف صفار البيض واخلطهم حتى يمتزجوا.",
      "اترك الوعاء فوق الماء الساخن (وليس على نار هادئة) للحفاظ على الشوكولاتة دافئة أثناء خفق بياض البيض.",
      "ضع 2 بياض بيض في وعاء الخلط. أضف كريم التارتار. خفقت حتى يبدأ الخليط في التكاثف ويبقى رذاذ من الخفق على السطح لمدة ثانية واحدة قبل أن يختفي في المزيج.",
      "أضف ثلث السكر واخفقه. اخفق في القليل من السكر لمدة 15 ثانية.",
      "اخفقي باقي السكر. استمر في الخفق حتى يصبح المزيج كثيفًا مثل كريم الحلاقة ويحتفظ بقمم ناعمة ، من 3 إلى 5 دقائق.",
      "  نقل أقل من نصف بياض البيض إلى الشوكولاتة.",
      "امزج حتى يندمج بياض البيض جيدًا في الشوكولاتة",
      "أضف باقي بياض البيض. قم بطي الشوكولاتة برفق باستخدام ملعقة ، ثم ارفعها من الأسفل واطويها.",
      "توقف عن الخلط بعد اختفاء بياض البيض. يقسم الخليط بين 2 رامكين جاهز. ضع القوالب على صينية خبز مُجهزة. ",
      "اخبزيها في فرن مسخن مسبقًا حتى تنفخ المشاجرات وترتفع فوق قمة الحافات ، من 12 إلى 15 دقيقة",
    ],
    "steps-m10": [
      "اغسل وقشر واقطع الهليون ،",
      "طبخ في ماء مملح",
      "ملح وفلفل الهليون",
      "تحميص الصنوبر",
      "قطع الطماطم إلى نصفين",
      "تخلط مع الهليون والسلطة والتتبيلة",
      "تقدم مع الرغيف الفرنسي",
    ],
  };
  Map<String, Object> textsEn = {
    "start": "GET STARTED",
    "Tap back again to leave": "Tap back again to leave",
    'Saved successfully': 'Saved successfully',
    "drawer_name": "Cooking Up!",
    "drawer_item1": "Meal",
    "drawer_item2": "Filters",
    "drawer_item3": "Themes",
    "drawer_switch_title": "Choose your language:",
    "drawer_switch_item1": "English",
    "drawer_switch_item2": "Arabic",
    "theme_appBar_title": "Your Themes",
    "theme_screen_title": "Adjust your themes selection.",
    "theme_mode_title": "Choose your Theme Mode",
    "System_default_theme": "System Default Theme",
    "light_theme": "Light Theme",
    "dark_theme": "Dark Theme",
    "primary": "Choose your primary color",
    "accent": "Choose your accent color",
    "filters_appBar_title": "Your Filters",
    "filters_screen_title": "Adjust your meal selection.",
    "Save": "Save",
    "Gluten-free": "Gluten-free",
    "Gluten-free-sub": "Only include gluten-free meals.",
    "Lactose-free": "Lactose-free",
    "Lactose-free_sub": "Only include Lactose-free meals.",
    "Vegetarian": "Vegetarian",
    "Vegetarian-sub": "Only include vegetarian meals.",
    "Vegan": "Vegan",
    "Vegan-sub": "Only include Vegan meals.",
    "categories": "Categories",
    "your_favorites": "Your Favorites",
    "cat-c1": "Italian",
    "cat-c2": "Spanish",
    "cat-c3": "French",
    "cat-c4": "Greek",
    "cat-c5": "British",
    "cat-c6": "Chinese",
    "cat-c7": "Indian",
    "cat-c8": "Japanese",
    "cat-c9": "Thailand",
    "cat-c10": "United States of America",
    "cat-c11": "Mexico",
    "cat-c12": "Brazil",
    "cat-c13": "Argentina",
    "cat-c14": "Morocco",
    "cat-c15": "Lebanon",
    "cat-c16": "Tunisia",
    "cat-c17": "Algeria",
    "cat-c18": "Egypt",
    "cat-c19": "Syria",
    "cat-c20": "South Africa",
    "Complexity.Simple": "Simple",
    "Complexity.Challenging": "Challenging",
    "Complexity.Hard": "Hard",
    "Affordability.Affordable": "Affordable",
    "Affordability.Pricey": "Pricey",
    "Affordability.Luxurious": "Luxurious",
    "min": "min",
    "min2": "min",
    "meal-m1": "Lasagna With Minced Meat",
    "meal-m2": "Risotto",
    "meal-m3": "Spaghetti Carbonara",
    "meal-m4": "Wiener Schnitzel",
    "meal-m5": "Salad with Smoked Salmon",
    "meal-m6": "Delicious Orange Mousse",
    "meal-m7": "Pancakes",
    "meal-m8": "Creamy Indian Chicken Curry",
    "meal-m9": "Chocolate Souffle",
    "meal-m10": "Asparagus Salad with Cherry Tomatoes",
    "Ingredients": "Ingredients",
    "Steps": "Steps",
    "favorites_text": "You have no favorites yet - start adding some!",
    "ingredients-m1": [
      'Lasagna slices',
      '500 gm ground beef',
      'Two onions, chopped',
      'Two minced garlic pieces',
      'A cup of shredded mozzarella cheese',
      '1/2 cup shredded parmesan cheese',
      'Tomato sauce cup',
      'A tablespoon of tomato paste',
      '100g butter',
      'A small spoon of basil',
      '1/2 teaspoon black pepper',
      'Pinch of salt',
    ],
    "ingredients-m2": [
      '3 cups of water',
      '2 cups and a third of chicken broth',
      'A quarter cup of butter',
      'Half an onion, chopped',
      'A cup of rice',
      'Half a cup of cooking cream',
      'A quarter cup grated Parmesan cheese',
      'salt and pepper as needed',
      'Chopped parsley, to garnish',
    ],
    "ingredients-m3": [
      'Bacon chopped turkey - 100 gr',
      'Parmesan cheese - 100 gr',
      'Eggs - 3',
      'Thin spaghetti pasta - 350 gr',
      'Peeled garlic - 2 lobes',
      'Unsalted butter - 50 gr',
      'Salt - to taste',
      'Pepper - to taste',
    ],
    "ingredients-m4": [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    "ingredients-m5": [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    "ingredients-m6": [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    "ingredients-m7": [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    "ingredients-m8": [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    "ingredients-m9": [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    "ingredients-m10": [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    "steps-m1": [
      'The bechamel is prepared by placing a pot on the fire, then melting the butter cubes in it, adding the flour, and stirring with a wooden spoon until all the butter is absorbed.',
      ' Put the milk gradually, stirring while pouring it, so that no lumps come inside the bechamel, When the mixture becomes homogeneous, turn off the heat and add black pepper and salt',
      ' As for the lasagna filling, we put another bowl on the fire, and melt the butter cubes in it, then add the onion and chopped garlic and fry until soft.',
      'Add the meat and fry until it changes color, then season with cinnamon, black pepper and salt, and mix well.',
      'Add tomato paste and sauce, put water on the meat and leave it on a low heat with stirring, until the meat is completely cooked and removed from the fire.',
      'We prepare a glass oven tray, and pour a layer of bechamel, covered with a layer of lasagna slices, and spread a layer of the filling and then another layer of bechamel and above it a layer of mozzarella cheese, the process is repeated until the amount is finished.',
      'Sprinkle Parmesan cheese on top, then put the tray in the oven, and leave for 25 to 30 minutes.',
      ' Take it out of the oven and serve hot.',
    ],
    "steps-m2": [
      'Heat the water and broth over medium heat until it boils, reduce the heat and leave it on the stove.',
      'Melt 2 tablespoons of butter in a saucepan over medium heat, add onions, and stir until wilted.',
      'Add the rice and stir for two minutes, then add a third of a cup of the broth and water mixture, and stir until absorbed.',
      'Raise the heat on the stove and add another cup of broth, then put the saucepan on the stove without covering it until all the liquids are absorbed.',
      'Repeat this step by adding a cup of broth each time and waiting until it is absorbed until the amount of broth ends.',
      'Let it steep for 25 minutes, until it becomes creamy.',
      'Add the cream, cheese, salt, pepper and the rest of the butter, stir for two minutes.',
      'Garnish with parsley and serve.',
    ],
    "steps-m3": [
      'In a bowl, beat the eggs, then sprinkle with pepper and mix. Leave the mixture aside.',
      'Put a pot of water on the fire until it boils.',
      'Add a teaspoon of salt to boiling water.',
      'Put the pasta and leave it until the water boils again.',
      'Cover the pot and leave the pasta for about 10 minutes or until it is done.',
      'Mash the garlic a little with the smooth side of the knife.',
      'In a frying pan, melt the butter and fry the bacon and garlic for about 5 minutes, until the turkey pieces are done.',
      'Take the garlic out of the pan and reduce the heat under the skillet.',
      'When the pasta is done, take it out with the pasta spoon, drain it from its water, and then put it in the skillet over the bacon.',
      'Mix parmesan cheese with the scrambled eggs.',
      'Turn off the heat under the pan.',
      'Pour the egg mixture over the pasta.',
      'Mix the pasta together until blended.',
      'Season with salt and pepper to taste.',
      'Serve the pasta immediately, with more cheese and black pepper spread over the top.',
    ],
    "steps-m4": [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    "steps-m5": [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    "steps-m6": [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    "steps-m7": [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    "steps-m8": [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    "steps-m9": [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    "steps-m10": [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
  };

  changeLan(bool lan) async {
    isEn = lan;
    notifyListeners();
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setBool("isEn", isEn);
  }

  getLan() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    isEn = prefs.getBool("isEn") ?? true;
    notifyListeners();
  }

  Object getTexts(String txt) {
    if (isEn == true) return textsEn[txt];
    return textsAr[txt];
  }
}
